<div class="jumbotron">
    <h1>Welcome to the CQRS TODO Example Application</h1>
    <p>powered by  <span class="zf-green">Zend Framework 2</span> and the crafics/cqrs-php library</p>
    <p>This simple TODO Application show you the basics of using Command Query Responsibility Segregation (CQRS) principles within a ZF2 Application</p>
    <p>The crafics/cqrs-php library is seamlessly integrated via <a href="https://github.com/codeliner/zf2-cqrs-module" target="_blank">codeliner/zf2-cqrs-module</a></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/crafics/cqrs-php" target="_blank"><?php echo $this->translate('Fork crafics/cqrs-php on GitHub') ?> &raquo;</a></p>
</div>