<div class="jumbotron">
    <h1>Welcome to the Malocher CQRS TODO Example Application</h1>
    <p>powered by  <span class="zf-green">Zend Framework 2</span> and the malocher/cqrs-esb library</p>
    <p>This simple TODO Application show you the basics of using Command Query Responsibility Segregation (CQRS) principles within a ZF2 Application</p>
    <p>The malocher/cqrs-esb library is seamlessly integrated via <a href="https://github.com/malocher/zf2-cqrs-module" target="_blank">malocher/zf2-cqrs-module</a></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/malocher/cqrs-esb" target="_blank"><?php echo $this->translate('Fork malocher/cqrs-esb on GitHub') ?> &raquo;</a></p>
</div>